[font]
size = 13.0
offset.y = 3

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

# Colors (Tomorrow Night with modified background)

# Default colors
[colors.primary]
background = '#151515'
foreground = '#c5c8c6'

[colors.cursor]
text = '#1d1f21'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black = '#1d1f21'
red = '#cc6666'
green = '#b5bd68'
yellow = '#e6c547'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#70c0ba'
white = '#373b41'

# Bright colors
[colors.bright]
black = '#666666'
red = '#ff3334'
green = '#9ec400'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b77ee0'
cyan = '#54ced6'
white = '#282a2e'

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
option_as_alt = "OnlyLeft"
