[font]
size = 14.0
offset.y = 3

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
option_as_alt = "OnlyLeft"

# Colors (Tokyo Night Storm variant)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#9699a8'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'
