[font]
size = 14.0
offset.y = 3

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
option_as_alt = "OnlyLeft"

# Colors (Solarized Osaka)
# Source https://github.com/craftzdog/solarized-osaka.nvim

# Default colors
[colors.primary]
background = '#001a1d'
foreground = '#839496'

# Normal colors
[colors.normal]
black = '#073642'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#d33682'
cyan = '#2aa198'
white = '#eee8d5'

# Bright colors
[colors.bright]
black = '#4c4c4c'
red = '#cb4b16'
green = '#586e75'
yellow = '#657b83'
blue = '#839496'
magenta = '#6c71c4'
cyan = '#93a1a1'
white = '#fdf6e3'
